### ISSUE TITLE
Tracking issue: experimental ink! contract support for Bitcoin smart contracts

### ISSUE THREAD

**Issue by nud3l** [interlay/interbtc#983]
**Is your feature request related to a problem? Please describe.**
Developing smart contracts with Bitcoin capabilities relies on using Solidity and the EVM mostly. We can offer developers Rust contracts with ink! using the `contracts` pallet and giving it access to the BTC-relay.

**Describe the solution you'd like**
Implement a proof of concept of ink! Bitcoin contracts.

- [ ] Add the `contracts` pallet to the testnet runtimes
- [ ] Give the contracts pallet access to the BTC relay functions (verify transactions)
- [ ] Implement a POC smart contract that verifies a Bitcoin transaction.

**Describe alternatives you've considered**
None.

**Additional context**

Maybe, we should address #605 first to not break the interface directly.

**Comment by sander2** [comment]
POC delivered here: https://github.com/interlay/interbtc/pull/990
Closing this issue.
